### ISSUE TITLE
help/program inconsistency

### ISSUE THREAD

**Issue by PeterNerlich** [7HAL32/robolab-deploy#3]
When running the deploy script the (n>1)th time, it claims
```
INFO: If you have to change the IP or password, run
      ./deploy.py -n
```
However, typing `./deploy.py -n` or `python3 deploy.py` throws
```
RoboLab deploy script v.1.2.0
usage: deploy.py [-h] [-c] [-e] [-b]
deploy.py: error: unrecognized arguments: -n
```

**Comment by lutzthies** [comment]
Seems you are way behind the current HEAD. The typo has been fixed prior to the public release tomorrow morning in [5be6721](https://github.com/7HAL32/robolab-deploy/commit/5be67214e3693222f825e3207b9baabf2c71359f). The version you have obtained was not intended for any other purpose than debugging and testing. Please update the template as well as the submodule according to the provided instructions. Thank you.

**Comment by PeterNerlich** [comment]
I typed `git pull template spring-17` as well as
```
$ git submodule foreach git pull origin master
$ git add robolab-deploy
fatal: Pathspec 'robolab-deploy' is in submodule 'robolab-deploy'
$ git commit -m "updated submodule to lastest version of the upstream head"
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
$ git push
Everything up-to-date
```
from within the root of the git repo, though only the template itself found commits I suppose got pushed mere minutes after I last checked. I would like to ask for assistance.

```
$ git remote -v
origin    [...]
template	https://github.com/7HAL32/robolab-template (fetch)
template	https://github.com/7HAL32/robolab-template (push)
```

**Comment by krabo0om** [comment]
Go into your robolab-deploy directory inside the robolab-template and try `git pull template master` to get the latest version of the deploy script

**Comment by PeterNerlich** [comment]
Okay, this is resolved, I tried a lot and came to different conclusion, **_this is just FYI_** — by renaming the folder of the template after cloning some paths appear to have been damaged, rendering the submodule unrecognizable as "not a git repository". At least I conclude that, after cloning the current template to a different folder and manually copying the submodule over, encountering and figuring out exactly this problem. After manually fixing this, the @krabo0om's suggestion as well as the documented way worked as intended.
